[package]
name = "auth"
version = "0.1.0"
edition = "2024"
license = "MPL-2.0"
authors = ["Zsolt Krüpl"]

[features]
default = ["ldap", "redis"]
ldap = ["dep:ldap3"]
redis = ["data/redis"]

[dependencies]
ldap3 = { workspace = true, default-features = false, optional = true, features = ["tls-rustls-ring"] }
rand = { workspace = true }
subtle = { workspace = true }
sha2 = { workspace = true }
argon2 = { workspace = true }
tokio = { workspace = true, features = ["time", "macros", "rt-multi-thread"] }
totp-rfc = { workspace = true }

data = { path = "../data", default-features = false, features = ["db-sqlite"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
