mod action_flash;
mod action_statements;
mod action_transaction;
mod artifact_contract;
pub use artifact_contract::runtime_contract_fingerprint;
mod authorization;
mod budget_security;
pub mod codegen;
mod compile_api;
mod critical_declarations;
mod critical_security;
mod domain_refinement;
mod domain_symbols;
mod domain_types;
mod domain_validation;
mod effect_security;
mod expression_postfix;
mod expression_security;
mod expression_type;
mod generic_type_syntax;
mod handler_parser;
mod handler_security;
mod handler_signature;
mod handler_types;
mod html_template;
mod idempotency_security;
mod inherent_impl;
mod input_security;
mod integration_declarations;
mod library_surface;
mod mfa_security;
mod model_security;
mod module_header;
mod module_namespace;
mod mutation_security;
mod outbound_calls;
mod outbound_security;
mod package_manifest;
mod page_canonical;
mod page_statements;
mod permission_declarations;
mod permission_security;
mod production_declarations;
mod public_errors;
mod public_projection;
mod pure_calls;
mod pure_functions;
mod pure_struct_return;
mod query_mutation_contract;
mod query_parser;
mod response_contract;
mod response_security;
mod rust_method_registry;
mod rust_surface_security;
mod rust_surface_syntax;
mod scalar_security;
mod schema_declarations;
mod secret_usage;
mod security_event_declarations;
mod source_cache;
mod source_discovery;
mod source_loader;
mod source_snapshot;
mod source_syntax;
mod sql_syntax;
mod statement_helpers;
mod sum_expression;
mod sum_match;
mod template_declarations;
mod tenant_security;
mod tenant_sql;
mod type_resolution;
mod type_semantics;
mod typed_json_response;
mod upload_security;
mod webhook_declarations;
mod webhook_security;
pub use compile_api::{
    CompiledFile, CompiledSource, VerifiedCompileError, compile_file,
    compile_file_with_dependencies, compile_source, compile_verified_file, compile_verified_source,
};
pub use diagnostics::CompileError;
use language_core::Program;
pub use source_cache::{CompilerCacheStats, stats as compiler_cache_stats};
mod compile_pipeline;

fn compile_units(units: &[source_loader::SourceUnit]) -> Result<Program, CompileError> {
    compile_pipeline::compile_units(units)
}

mod action_response_tail;
mod arrays;
mod builtin_registry;
mod builtin_types;
mod cache_safety;
mod control_flow;
mod credential_builtin_types;
mod declarations;
mod diagnostics;
mod dicts;
mod domain_objects;
mod expression;
mod expression_parser;
mod expression_primary;
mod expression_token;
mod lexer;
mod math_builtin_types;
mod page_response_tail;
mod query_resource_security;
mod regex_types;
mod route_budget;
mod route_cache;
mod route_calls;
mod route_multipart;
mod route_page_policy;
mod route_security;
mod route_tenant;
mod route_typed_schema;
mod route_upload;
mod routes;
mod rustlike_surface;
mod safe_html_types;
mod string_builtin_signature;
mod string_builtin_types;
#[cfg(test)]
mod tests;
mod validation_rules;
mod visibility;
