[package]
name = "integrations"
version = "0.1.0"
edition = "2024"
license = "MPL-2.0"
authors = ["Zsolt Krüpl"]

[dependencies]
ipnet = { workspace = true }
rustls = { workspace = true }
tokio = { workspace = true, features = ["net", "io-util", "time", "sync"] }
tokio-rustls = { workspace = true }
webpki-roots = { workspace = true }
serde = { workspace = true, features = ["derive"] }
toml = { workspace = true }
libc = { workspace = true }
